version: '3.7'
services:
  quarkus:
    image: maven
    restart: always
    ports:
      - 8080:8080
    volumes:
      - "./sys-tarefa:/app"
      - "~/.m2:/root/.m2"
    working_dir: /app
    command: mvn quarkus:dev
  front:
    build: fattocs-web-page
    ports:
      - 80:80
  db:
    build: db
    ports:
      - 5432:5432
  


